### PR TITLE
Remove BSON marshalling logic

### PR DESCRIPTION
**Pull request by pdyraga**
Depends on #1 
Refs https://github.com/keep-network/keep-core/issues/115

We use a different mechanism for data marshaling and don't want to have a dead BSON-oriented code with a mandatory dependency to `gopkg.in/mgo.v2/bson`.

### CODE REVIEW

**Comment by mhluongo** [comment]
Should we open a PR to upstream before we merge this?

**Comment by Shadowfiend** [comment]
With the commits from the previous branch, you mean?

**Comment by mhluongo** [comment]
I do.

**Comment by Shadowfiend** [comment]
Yeah, I think that's perfectly fair. If we want to move forward on this PR in the meantime, we'll probably want to branch `master` and issue a PR off of that new branch, otherwise merging to `master` will update the PR on the original repo.

Worth noting the original repo is dormant since 2015, so it could end up being a minute before anyone gets a chance to look at the PR.

**Comment by pdyraga** [comment]
On the other hand, we want to remove JSON serialization logic in this PR and I am not sure original author will agree on it. We may end up with two versions anyway.

**Comment by mhluongo** [comment]
Oh we definitely will, just figured we should contribute the non-controversial stuff back before we split.

**Comment by pdyraga** [comment]
Yeah, it makes sense 💯 

I'll open yet one PR to our fork, this time touching threshold part. Let's maybe do the following: when we agree on a new PR and merge it, I'll branch our `master` to `almost-master` :wink: and open a PR to the original repo from `almost-master` branch.

For now, let's not merge this PR and leave it for the very end. 

This way, we should have all PRs in our `master`, including BSON removal and we should have two PRs polishing Paillier code in `almost-master`, without BSON removal, with a PR to the original repo.

**Comment by pdyraga** [comment]
I opened PR to the original repository so we can go ahead here.

**Comment by rargulati** [comment]
Looks good to me!

**Comment by pdyraga** [comment]
Closing this one in favor of #4

**Pull request closed without merging**
